## Generated SDC file "mp3.out.sdc"

## Copyright (C) 1991-2014 Altera Corporation
## Your use of Altera Corporation's design tools, logic functions 
## and other software and tools, and its AMPP partner logic 
## functions, and any output files from any of the foregoing 
## (including device programming or simulation files), and any 
## associated documentation or information are expressly subject 
## to the terms and conditions of the Altera Program License 
## Subscription Agreement, Altera MegaCore Function License 
## Agreement, or other applicable license agreement, including, 
## without limitation, that your use is for the sole purpose of 
## programming logic devices manufactured by Altera and sold by 
## Altera or its authorized distributors.  Please refer to the 
## applicable agreement for further details.


## VENDOR  "Altera"
## PROGRAM "Quartus II"
## VERSION "Version 13.1.4 Build 182 03/12/2014 SJ Full Version"

## DATE    "Mon Oct  8 07:49:37 2018"

##
## DEVICE  "EP3SE80F1152C2"
##


#**************************************************************
# Time Information
#**************************************************************

set_time_format -unit ns -decimal_places 3



#**************************************************************
# Create Clock
#**************************************************************

create_clock -name {clk} -period 10.000 -waveform { 0.000 5.000 } [get_ports {clk}]


#**************************************************************
# Create Generated Clock
#**************************************************************



#**************************************************************
# Set Clock Latency
#**************************************************************



#**************************************************************
# Set Clock Uncertainty
#**************************************************************

set_clock_uncertainty -rise_from [get_clocks {clk}] -rise_to [get_clocks {clk}]  0.020  
set_clock_uncertainty -rise_from [get_clocks {clk}] -fall_to [get_clocks {clk}]  0.020  
set_clock_uncertainty -fall_from [get_clocks {clk}] -rise_to [get_clocks {clk}]  0.020  
set_clock_uncertainty -fall_from [get_clocks {clk}] -fall_to [get_clocks {clk}]  0.020  


#**************************************************************
# Set Input Delay
#**************************************************************

set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {clk}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[0]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[1]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[2]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[3]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[4]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[5]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[6]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[7]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[8]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[9]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[10]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[11]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[12]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[13]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[14]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[15]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[16]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[17]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[18]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[19]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[20]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[21]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[22]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[23]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[24]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[25]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[26]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[27]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[28]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[29]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[30]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[31]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[32]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[33]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[34]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[35]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[36]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[37]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[38]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[39]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[40]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[41]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[42]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[43]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[44]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[45]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[46]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[47]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[48]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[49]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[50]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[51]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[52]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[53]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[54]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[55]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[56]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[57]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[58]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[59]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[60]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[61]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[62]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[63]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[64]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[65]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[66]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[67]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[68]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[69]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[70]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[71]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[72]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[73]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[74]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[75]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[76]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[77]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[78]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[79]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[80]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[81]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[82]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[83]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[84]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[85]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[86]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[87]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[88]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[89]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[90]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[91]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[92]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[93]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[94]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[95]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[96]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[97]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[98]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[99]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[100]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[101]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[102]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[103]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[104]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[105]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[106]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[107]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[108]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[109]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[110]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[111]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[112]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[113]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[114]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[115]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[116]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[117]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[118]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[119]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[120]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[121]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[122]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[123]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[124]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[125]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[126]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[127]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[128]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[129]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[130]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[131]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[132]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[133]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[134]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[135]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[136]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[137]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[138]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[139]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[140]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[141]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[142]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[143]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[144]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[145]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[146]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[147]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[148]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[149]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[150]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[151]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[152]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[153]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[154]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[155]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[156]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[157]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[158]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[159]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[160]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[161]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[162]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[163]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[164]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[165]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[166]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[167]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[168]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[169]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[170]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[171]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[172]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[173]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[174]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[175]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[176]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[177]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[178]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[179]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[180]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[181]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[182]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[183]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[184]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[185]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[186]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[187]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[188]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[189]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[190]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[191]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[192]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[193]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[194]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[195]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[196]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[197]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[198]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[199]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[200]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[201]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[202]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[203]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[204]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[205]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[206]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[207]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[208]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[209]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[210]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[211]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[212]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[213]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[214]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[215]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[216]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[217]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[218]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[219]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[220]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[221]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[222]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[223]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[224]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[225]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[226]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[227]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[228]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[229]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[230]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[231]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[232]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[233]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[234]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[235]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[236]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[237]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[238]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[239]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[240]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[241]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[242]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[243]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[244]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[245]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[246]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[247]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[248]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[249]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[250]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[251]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[252]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[253]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[254]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {rdata[255]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {resp}]


#**************************************************************
# Set Output Delay
#**************************************************************

set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {address[0]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {address[1]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {address[2]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {address[3]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {address[4]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {address[5]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {address[6]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {address[7]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {address[8]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {address[9]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {address[10]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {address[11]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {address[12]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {address[13]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {address[14]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {address[15]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {address[16]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {address[17]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {address[18]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {address[19]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {address[20]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {address[21]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {address[22]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {address[23]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {address[24]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {address[25]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {address[26]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {address[27]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {address[28]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {address[29]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {address[30]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {address[31]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {read}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[0]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[1]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[2]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[3]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[4]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[5]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[6]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[7]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[8]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[9]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[10]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[11]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[12]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[13]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[14]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[15]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[16]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[17]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[18]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[19]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[20]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[21]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[22]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[23]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[24]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[25]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[26]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[27]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[28]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[29]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[30]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[31]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[32]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[33]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[34]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[35]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[36]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[37]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[38]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[39]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[40]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[41]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[42]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[43]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[44]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[45]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[46]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[47]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[48]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[49]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[50]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[51]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[52]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[53]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[54]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[55]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[56]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[57]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[58]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[59]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[60]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[61]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[62]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[63]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[64]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[65]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[66]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[67]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[68]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[69]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[70]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[71]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[72]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[73]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[74]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[75]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[76]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[77]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[78]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[79]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[80]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[81]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[82]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[83]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[84]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[85]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[86]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[87]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[88]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[89]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[90]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[91]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[92]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[93]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[94]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[95]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[96]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[97]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[98]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[99]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[100]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[101]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[102]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[103]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[104]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[105]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[106]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[107]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[108]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[109]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[110]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[111]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[112]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[113]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[114]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[115]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[116]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[117]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[118]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[119]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[120]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[121]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[122]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[123]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[124]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[125]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[126]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[127]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[128]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[129]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[130]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[131]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[132]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[133]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[134]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[135]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[136]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[137]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[138]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[139]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[140]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[141]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[142]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[143]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[144]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[145]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[146]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[147]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[148]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[149]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[150]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[151]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[152]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[153]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[154]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[155]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[156]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[157]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[158]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[159]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[160]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[161]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[162]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[163]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[164]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[165]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[166]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[167]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[168]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[169]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[170]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[171]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[172]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[173]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[174]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[175]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[176]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[177]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[178]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[179]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[180]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[181]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[182]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[183]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[184]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[185]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[186]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[187]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[188]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[189]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[190]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[191]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[192]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[193]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[194]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[195]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[196]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[197]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[198]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[199]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[200]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[201]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[202]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[203]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[204]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[205]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[206]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[207]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[208]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[209]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[210]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[211]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[212]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[213]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[214]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[215]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[216]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[217]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[218]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[219]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[220]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[221]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[222]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[223]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[224]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[225]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[226]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[227]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[228]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[229]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[230]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[231]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[232]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[233]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[234]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[235]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[236]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[237]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[238]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[239]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[240]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[241]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[242]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[243]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[244]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[245]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[246]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[247]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[248]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[249]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[250]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[251]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[252]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[253]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[254]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {wdata[255]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  0.000 [get_ports {write}]


#**************************************************************
# Set Clock Groups
#**************************************************************



#**************************************************************
# Set False Path
#**************************************************************



#**************************************************************
# Set Multicycle Path
#**************************************************************



#**************************************************************
# Set Maximum Delay
#**************************************************************



#**************************************************************
# Set Minimum Delay
#**************************************************************



#**************************************************************
# Set Input Transition
#**************************************************************

